In [1]:
import numpy as np
a=np.array([[1, 2, 3], [4, 5, 6]])
print('array using list:\n',a)

array using list:
 [[1 2 3]
 [4 5 6]]


In [2]:
b=np.array((1 , 3, 2))
print('array using tuple:\n',b)

array using tuple:
 [1 3 2]


In [3]:
c=np.zeros((3, 4))
print("array created with all zeros:\n", c)

array created with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
d=np.random.random((3,3))
print('random array:\n',d)

random array:
 [[0.63904363 0.29069514 0.17288428]
 [0.61609446 0.37321819 0.91920532]
 [0.9382027  0.11701766 0.97947762]]


In [5]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[:2,:2]
temp

array([[-1. ,  2. ],
       [ 4. , -0.5]])

In [6]:
a=np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print('original array:\n',a)
print('transpose array:\n',a.T)

original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
transpose array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
